---
development:
  DB_FILENAME: db/local/dev.db
  spotify_Client_ID: provision_spotify_api_ID
  spotify_Client_secret: provision_spotify_api_secret
  spotify_gettoken_time: provision_gettoken_time
  spotify_temp_token: provision_spotify_api_temp_token

test:
  DB_FILENAME: db/local/test.db
  spotify_Client_ID: provision_spotify_api_ID
  spotify_Client_secret: provision_spotify_api_secret
  spotify_gettoken_time: provision_gettoken_time
  spotify_temp_token: provision_spotify_api_temp_token

production:
  spotify_Client_ID: provision_spotify_api_ID
  spotify_Client_secret: provision_spotify_api_secret
  spotify_gettoken_time: provision_gettoken_time
  spotify_temp_token: provision_spotify_api_temp_token
